### ISSUE TITLE
I can't implement the example in the tutorial . I cant use `with`.【Redlock】

### ISSUE THREAD

**Issue by Jerry95two7** [brainix/pottery#697]
![image](https://user-images.githubusercontent.com/52588515/202679974-730f883b-d24e-4c85-a2e5-020e8746d204.png)

I cant use `with`.

console output
```
Traceback (most recent call last):
  File "/Users/fanren/pokerwinners/config/redis_info.py", line 57, in <module>
    r_lock.release()
  File "/opt/miniconda3/envs/pkwinners/lib/python3.8/site-packages/pottery/redlock.py", line 673, in __exit__
    self.__release()
  File "/opt/miniconda3/envs/pkwinners/lib/python3.8/site-packages/pottery/redlock.py", line 595, in release
    raise ReleaseUnlockedLock(
pottery.exceptions.ReleaseUnlockedLock: ('redlock:printer', frozenset({Redis<ConnectionPool<Connection<host=127.0.0.1,port=6379,db=2>>>}))
printer_lock is locked
False
printer_lock is locked
```

**Comment by brainix** [comment]
Hi, @Jerry95two7!

Inside your `with` block, don’t release the lock. 

The whole point of a context manager is that you don’t have to worry about setup or tear down. The lock acquisition is implicit, and the lock release is implicit as well. 

Does that help to resolve your issue?

Thank you!

**Comment by Jerry95two7** [comment]
@brainix  thanks
