### ISSUE TITLE
gevent.hub.LoopExit:  This operation would block forever' error

### ISSUE THREAD

**Issue by Sorrow2** [brainix/pottery#7]
Hello.
I keep getting this error last two days. It worked fine before.
Maybe it because i did upgrade all my python libs. Any ideas how i can fix this?

```
Exception in thread Thread-20:
Traceback (most recent call last):
  File "/usr/lib/python3.4/threading.py", line 920, in _bootstrap_inner
    self.run()
  File "/usr/lib/python3.4/threading.py", line 868, in run
    self._target(*self._args, **self._kwargs)
  File "/usr/local/lib/python3.4/dist-packages/telegram/ext/dispatcher.py", line 61, in pooled
    result = func(*pargs, **kwargs)
  File "main.py", line 149, in any_message
    if user_id in users_dict:
  File "/usr/local/lib/python3.4/dist-packages/pottery/dict.py", line 83, in __contains__
    return bool(self.redis.hexists(self.key, self._encode(key)))
  File "/usr/local/lib/python3.4/dist-packages/redis/client.py", line 1853, in hexists
    return self.execute_command('HEXISTS', name, key)
  File "/usr/local/lib/python3.4/dist-packages/redis/client.py", line 573, in execute_command
    return self.parse_response(connection, command_name, **options)
  File "/usr/local/lib/python3.4/dist-packages/redis/client.py", line 585, in parse_response
    response = connection.read_response()
  File "/usr/local/lib/python3.4/dist-packages/redis/connection.py", line 577, in read_response
    response = self._parser.read_response()
  File "/usr/local/lib/python3.4/dist-packages/redis/connection.py", line 238, in read_response
    response = self._buffer.readline()
  File "/usr/local/lib/python3.4/dist-packages/redis/connection.py", line 168, in readline
    self._read_from_socket()
  File "/usr/local/lib/python3.4/dist-packages/redis/connection.py", line 126, in _read_from_socket
    data = self._sock.recv(socket_read_size)
  File "/usr/local/lib/python3.4/dist-packages/gevent/_socket3.py", line 307, in recv
    self._wait(self._read_event)
  File "/usr/local/lib/python3.4/dist-packages/gevent/_socket3.py", line 147, in _wait
    self.hub.wait(watcher)
  File "/usr/local/lib/python3.4/dist-packages/gevent/hub.py", line 627, in wait
    result = waiter.get()
  File "/usr/local/lib/python3.4/dist-packages/gevent/hub.py", line 875, in get
    return self.hub.switch()
  File "/usr/local/lib/python3.4/dist-packages/gevent/hub.py", line 606, in switch
    return greenlet.switch(self)
gevent.hub.LoopExit: ('This operation would block forever', <Hub at 0x7f23460295a0 epoll pending=0 ref=0 fileno=43>)
```

**Comment by Sorrow2** [comment]
i think this is same as https://github.com/kennethreitz/grequests/issues/55
because i got this when i started to use grequests.

**Comment by brainix** [comment]
Thanks for discovering the root cause of the issue!  Multiprocessing/multithreading issues are hard to track down!
